schema_version: 1

context:
  name: pyccolo
  version: "0.0.80"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pyccolo-${{ version }}.tar.gz
  sha256: eb06d2493eb7b2595a825b7d1491d8a38f47b421e65b7e8706ce5ff98112c6fe

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - pyc = pyccolo.__main__:main
      - pyccolo = pyccolo.__main__:main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=48
    - setuptools-git-versioning
    - wheel >=0.30.0
  run:
    - python >=${{ python_min }}
    - traitlets
    - typing_extensions

tests:
  - python:
      imports:
        - pyccolo
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - pyc --help
      - pyccolo --help

about:
  summary: Declarative instrumentation for Python
  license: BSD-3-Clause
  license_file: docs/LICENSE.txt
  homepage: https://github.com/smacke/pyccolo

extra:
  recipe-maintainers:
    - thewchan
